name: 'Alpha Release'

on:
  pull_request:
    branches:
      - 'master'
    types: [closed]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && contains(github.event.pull_request.title, 'alpha')
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: cd ./browser && npm ci
    - name: 'Run build'
      run: cd ./browser && npm run build-dev ${{ github.event.pull_request.title }}
    - name: 'Generate release'
      run: cd ./browser && npm run generate-release alpha v=${{ github.event.pull_request.title }} token=${{ secrets.GITHUB_ACCESS_TOKEN }}
