name: 'Development'

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout dev'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: cd ./browser && npm ci
    - name: 'Run dev build'
      run: cd ./browser && npm run build-dev
    - name: 'Generate pre-release'
      run: cd ./browser && npm run generate-release dev token=${{ secrets.GITHUB_ACCESS_TOKEN }}