name: 'Development'

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout dev'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: cd ./browser && npm install
    - name: 'Run dev build'
      run: cd ./browser && npm run build-dev

  release:
    name: 'Release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Create release'
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          tag: 'TEST'
          body: 'body'
          prerelease: true
          files: >
            ./dist/chrome.zip
            ./dist/firefox.zip
            ./dist/palemoon.xpi
            ./dist/userscript.meta.js
            ./dist/userscript.user.js
