name: 'Stable Release'

on:
  pull_request:
    branches:
      - 'master'
    types: [closed]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && !contains(github.event.pull_request.title, 'alpha') && !contains(github.event.pull_request.title, 'beta')
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: cd ./browser && npm ci
    - name: 'Run build'
      run: cd ./browser && npm run build ${{ github.event.pull_request.title }}
    - name: 'Generate release'
      run: cd ./browser && npm run generate-release stable v=${{ github.event.pull_request.title }} token=${{ secrets.GITHUB_ACCESS_TOKEN }}
    - name: 'Upload to Chrome store'
      uses: trmcnvn/chrome-addon@v1
      with:
        extension: ${{ secrets.CHROME_EXTENSION_ID }}
        zip: ./browser/dist/chrome.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
    - name: 'Upload to Firefox store'
      uses: trmcnvn/firefox-addon@v1
      with:
        uuid: ${{ secrets.FIREFOX_EXTENSION_ID }}
        xpi: ./browser/dist/firefox.zip
        manifest: ./browser/build/firefox/manifest.json
        api-key: ${{ secrets.FIREFOX_CLIENT_ID }}
        api-secret: ${{ secrets.FIREFOX_CLIENT_SECRET }}
    - name: 'Upload to Pale Moon store'
      uses: rafaelgssa/palemoon-addon@v1
      with:
        slug: ${{ secrets.PALEMOON_EXTENSION_SLUG }}
        xpi: ./browser/dist/palemoon.xpi
        username: ${{ secrets.PALEMOON_USERNAME }}
        password: ${{ secrets.PALEMOON_PASSWORD }}
